### ISSUE TITLE
Aspect Tracker does not update on scene change

### ISSUE THREAD

**Issue by saif-ellafi** [Galdormin/FoundryVTT-Fate-Aspect-Tracker#11]
1. Open the Aspect Tracker
2. Change Scene

You will notice you will still see the aspects of previous scene

**Comment by Galdormin** [comment]
I don't have this issue on my side...

Maybe because the aspect in your tracker are from older version. You could try : 

1. Edit the aspect and change the source to `general`. Then you edit it again and put it to `scene`
2. Delete the aspect and try with new one.

If both of those options didn't work, you can send me the value of the scene flag and the `_aspect_tracker` journal entry.
You can get the scene flags but running `game.scenes.viewed.getFlag("fate-aspect-tracker", "aspects")` in the command line.

**Comment by saif-ellafi** [comment]
Sorry, I had 0.4.1 installed. Not happening in 0.5.0
